### ISSUE TITLE
As an admin, I want to sign in without being asked to provide a DUNS or SAM number,

### ISSUE THREAD

**Issue by adelevie** [18F/mpt3500#23]
As an admin,
I want to sign in without being asked to provide a DUNS or SAM number,
So that I don't enter un-needed information.

**Comment by baccigalupi** [comment]
https://github.com/18F/mpt3500/pull/35

This one builds on https://github.com/18F/mpt3500/pull/33 and that one should be reviewed altered and merged before this one.
