### ISSUE TITLE
Expand the README

### ISSUE THREAD

**Issue by khandelwal** [18F/mpt3500#5]
Flush out the README so that it's clear what's going on here. 

What does this software do? 
Why is it needed? 
What's the micro-purchase experiment?

If one wants to run a local copy of this, how does one do it?

**Comment by khandelwal** [comment]
The new README doesn't explain what this repository is for, or what this software does. What are it's features? Why is new software required for a micro-purchase experiment?

**Comment by blacktm** [comment]
How about this:

> This app will be used to manage bids for 18F's [micro-purchase threshold experiment](https://18f.gsa.gov/2015/10/13/open-source-micropurchasing/). Vendors will be able to view open issues and bid on them, given they have GitHub accounts and are registered on [SAM.gov](https://www.sam.gov).

As we add features, we'll document them. Also, not sure what's expected for "why software is required" – because we don't want to do this manually? Seems weird to explicitly say that.

**Comment by khandelwal** [comment]
That sentence works. Let's add it in (but please pull request).

**Comment by blacktm** [comment]
So just to be clear, our policy is to never ever commit to master, no matter how trivial (I'm seriously asking)?

**Comment by khandelwal** [comment]
Yes!

**Comment by blacktm** [comment]
LET IT BE SO. :godmode:

**Comment by blacktm** [comment]
Ok, so I've opened a PR to update the README at #26. What's the protocol for it merging into master? Do I have to wait for another member of 18F Consulting to review before merging, or can I self-review my own PR? If I'm confident in the PR and it passes all tests, can I merge the PR without review? With review, I'm I able to merge the PR myself, or should the the PR author never be allowed to merge their own PR?
